export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_NAME = 'SET_USER_NAME';

export const SET_INPUT_DATA = 'SET_INPUT_DATA'
export const SET_BUTTON_STATUS = 'SET_BUTTON_STATUS'

export const SET_VIEWING_QUESTION = 'SET_VIEWING_QUESTION'

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'